Add context.Context and other required params in api calls.
Lot many functions calls have been changed which cause the
upgrade failure when moving to v1.18.0.
This patch address those issues.

Example failure
```
pkg/util/k8scmcache.go:88:66: not enough arguments in call to k8scm.Client.CoreV1().ConfigMaps(k8scm.Namespace).Get

	have (string, "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions)

	want (context.Context, string, "k8s.io/apimachinery/pkg/apis/meta/v1".GetOptions)

pkg/util/k8scmcache.go:98:68: not enough arguments in call to k8scm.Client.CoreV1().ConfigMaps(k8scm.Namespace).List

	have ("k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions)

.......

```

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>