nfs: log error when go-ceph fails to create the export
With Ceph Tentacle creating a (the first?) NFS-export fails with:

```
Error EINVAL: Traceback (most recent call last):
    File "/usr/share/ceph/mgr/mgr_module.py", line 2010, in _handle_command
      return CLICommand.COMMANDS[cmd['prefix']].call(self, cmd, inbuf)
    File "/usr/share/ceph/mgr/mgr_module.py", line 534, in call
      return self.func(mgr, **kwargs)
    File "/usr/share/ceph/mgr/object_format.py", line 592, in _format_response
      robj = f(*args, **kwargs)
    File "/usr/share/ceph/mgr/nfs/module.py", line 45, in
_cmd_nfs_export_create_cephfs
      earmark_resolver = CephFSEarmarkResolver(self)
    File "/usr/share/ceph/mgr/mgr_util.py", line 356, in __init__
      self._cephfs_client = client or CephfsClient(mgr)
    File "/usr/share/ceph/mgr/mgr_util.py", line 318, in __init__
      self.connection_pool = CephfsConnectionPool(self.mgr)
    File "/usr/share/ceph/mgr/mgr_util.py", line 223, in __init__
      self.timer_task.start()
    File "/usr/lib64/python3.9/threading.py", line 899, in start
      _start_new_thread(self._bootstrap, ())
  RuntimeError: can't start new thread
```

It seems this can only happen when the CLI is used, that means go-ceph
failed to create the export in the first place. It would be useful to
log the go-ceph failure, so that improving is possible.

Signed-off-by: Niels de Vos <ndevos@ibm.com>